language: ruby
rvm:
  - 2.2.2

services:
  - redis-server

env:
  - DB=mysql

script:
  - bundle exec rake db:migrate --trace
  - bundle exec rake db:test:prepare
  - bundle exec rspec spec/

before_script:
  - cp config/database.travis.yml config/database.yml
  - mysql -e 'create database munkiserver_test;'

notifications:
  email:
    on_success: change # default: change
    on_failure: change # default: always
